# Generated by Django 3.1.5 on 2021-01-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=3)),
                ('date', models.DateField()),
                ('allergic', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=25)),
                ('vaccine', models.CharField(choices=[('1', 'Comirnaty'), ('2', 'Moderna COVID-19 Vaccine'), ('3', 'CoronaVac'), ('4', 'COVID-19 Vaccine AstraZeneca'), ('5', 'Sputnik V'), ('6', 'BBIBP-CorV'), ('7', 'EpiVacCorona'), ('8', 'Covaxin')], max_length=10)),
                ('symptoms', models.CharField(choices=[('fatigue', 'Fatigue'), ('headache', 'Headache'), ('pain', 'Muscle Pain'), ('fever', 'Fever'), ('Pain Around the Injection Site', (('swell', 'Swellness'), ('red', 'Redness'), ('sore', 'Soreness')))], max_length=10)),
                ('proof', models.FileField(upload_to='')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
