# Generated by Django 3.1.5 on 2021-01-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_auto_20210124_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergic',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
