# Generated by Django 3.1.5 on 2021-01-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0003_auto_20210124_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergic',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
