# Generated by Django 3.1.5 on 2021-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0004_auto_20210124_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.BooleanField(choices=[('fatigue', 'Fatigue'), ('headache', 'Headache'), ('pain', 'Muscle Pain'), ('fever', 'Fever'), ('Pain Around the Injection Site', (('swell', 'Swellness'), ('red', 'Redness'), ('sore', 'Soreness')))], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.CharField(choices=[('1', 'Pfizer'), ('2', 'Moderna COVID-19 Vaccine')], max_length=10),
        ),
    ]
