# Generated by Django 3.1.5 on 2021-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0005_auto_20210124_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_fatigue',
            field=models.BooleanField(default=False, verbose_name='Fatigue'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_fever',
            field=models.BooleanField(default=False, verbose_name='Fever'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_headache',
            field=models.BooleanField(default=False, verbose_name='Headache'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_muscle_pain',
            field=models.BooleanField(default=False, verbose_name='Muscle Pain'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pain_around',
            field=models.BooleanField(default=False, verbose_name='Pain Around Injection Site'),
        ),
    ]
